class LoadCountryData < ActiveRecord::Migration
  def up
  	Country.create(:description => "México", :active => true)
  	Country.create(:description => "Estados Unidos", :active => false)

  	State.create(:description => "Aguascalientes", :country_id => 1, :active => true)
  	State.create(:description => "Baja California", :country_id => 1, :active => true)
  	State.create(:description => "Baja California Sur", :country_id => 1, :active => true)
  	State.create(:description => "Campeche", :country_id => 1, :active => true)
  	State.create(:description => "Chiapas", :country_id => 1, :active => true)
  	State.create(:description => "Chihuahua", :country_id => 1, :active => true)
  	State.create(:description => "Coahuila", :country_id => 1, :active => true)
  	State.create(:description => "Colima", :country_id => 1, :active => true)
  	State.create(:description => "Distrito Federal", :country_id => 1, :active => true)
  	State.create(:description => "Durango", :country_id => 1, :active => true)
  	State.create(:description => "Estado de México", :country_id => 1, :active => true)
  	State.create(:description => "Guanajuato", :country_id => 1, :active => true)
  	State.create(:description => "Guerrero", :country_id => 1, :active => true)
  	State.create(:description => "Hidalgo", :country_id => 1, :active => true)
  	State.create(:description => "Jalisco", :country_id => 1, :active => true)
  	State.create(:description => "Michoacán", :country_id => 1, :active => true)
  	State.create(:description => "Morelos", :country_id => 1, :active => true)
  	State.create(:description => "Nayarit", :country_id => 1, :active => true)
  	State.create(:description => "Nuevo León", :country_id => 1, :active => true)
  	State.create(:description => "Oaxaca", :country_id => 1, :active => true)
  	State.create(:description => "Puebla", :country_id => 1, :active => true)
  	State.create(:description => "Querétaro", :country_id => 1, :active => true)
  	State.create(:description => "Quintana Roo", :country_id => 1, :active => true)
  	State.create(:description => "San Luis Potosí", :country_id => 1, :active => true)
  	State.create(:description => "Sinaloa", :country_id => 1, :active => true)
  	State.create(:description => "Sonora", :country_id => 1, :active => true)
  	State.create(:description => "Tabasco", :country_id => 1, :active => true)
  	State.create(:description => "Tamaulipas", :country_id => 1, :active => true)
  	State.create(:description => "Tlaxcala", :country_id => 1, :active => true)
  	State.create(:description => "Veracruz", :country_id => 1, :active => true)
  	State.create(:description => "Yucatán", :country_id => 1, :active => true)
  	State.create(:description => "Zacatecas", :country_id => 1, :active => true)

  	Location.create(:description => "Abasolo", :state_id => 19, :active => true)
  	Location.create(:description => "Agualeguas", :state_id => 19, :active => true)
  	Location.create(:description => "Allende", :state_id => 19, :active => true)
  	Location.create(:description => "Anáhuac", :state_id => 19, :active => true)
  	Location.create(:description => "Apodaca", :state_id => 19, :active => true)
  	Location.create(:description => "Aramberri", :state_id => 19, :active => true)
  	Location.create(:description => "Bustamante", :state_id => 19, :active => true)
  	Location.create(:description => "Cadereyta Jiménez", :state_id => 19, :active => true)
  	Location.create(:description => "Carmen", :state_id => 19, :active => true)
  	Location.create(:description => "Cerralvo", :state_id => 19, :active => true)
	  Location.create(:description => "China", :state_id => 19, :active => true)
  	Location.create(:description => "Ciénega de Flores", :state_id => 19, :active => true)
  	Location.create(:description => "Dr. Coss", :state_id => 19, :active => true)
  	Location.create(:description => "Dr. Arroyo", :state_id => 19, :active => true)
  	Location.create(:description => "Dr. González", :state_id => 19, :active => true)
  	Location.create(:description => "Galeana", :state_id => 19, :active => true)
  	Location.create(:description => "García", :state_id => 19, :active => true)
  	Location.create(:description => "Gral. Escobedo", :state_id => 19, :active => true)
  	Location.create(:description => "Gral. Terán", :state_id => 19, :active => true)
  	Location.create(:description => "Gral. Treviño", :state_id => 19, :active => true)
  	Location.create(:description => "Gral. Zaragoza", :state_id => 19, :active => true)
  	Location.create(:description => "Gral. Zuazua", :state_id => 19, :active => true)
  	Location.create(:description => "Gral. Bravo", :state_id => 19, :active => true)
  	Location.create(:description => "Guadalupe", :state_id => 19, :active => true)
  	Location.create(:description => "Hidalgo", :state_id => 19, :active => true)
  	Location.create(:description => "Higueras", :state_id => 19, :active => true)
  	Location.create(:description => "Hualahuises", :state_id => 19, :active => true)
  	Location.create(:description => "Iturbide", :state_id => 19, :active => true)
  	Location.create(:description => "Juárez", :state_id => 19, :active => true)
  	Location.create(:description => "Lampazos de Naranjo", :state_id => 19, :active => true)
  	Location.create(:description => "Linares", :state_id => 19, :active => true)
  	Location.create(:description => "Los Aldamas", :state_id => 19, :active => true)
  	Location.create(:description => "Los Herreras", :state_id => 19, :active => true)
  	Location.create(:description => "Los Ramones", :state_id => 19, :active => true)
  	Location.create(:description => "Marín", :state_id => 19, :active => true)
  	Location.create(:description => "Melchor Ocampo", :state_id => 19, :active => true)
  	Location.create(:description => "Mier y Noriega", :state_id => 19, :active => true)
  	Location.create(:description => "Mina", :state_id => 19, :active => true)
  	Location.create(:description => "Montemorelos", :state_id => 19, :active => true)
  	Location.create(:description => "Monterrey", :state_id => 19, :active => true)
  	Location.create(:description => "Parás", :state_id => 19, :active => true)
  	Location.create(:description => "Pesquería", :state_id => 19, :active => true)
  	Location.create(:description => "Rayones", :state_id => 19, :active => true)
  	Location.create(:description => "Sabinas Hidalgo", :state_id => 19, :active => true)
  	Location.create(:description => "Salinas Victoria", :state_id => 19, :active => true)
  	Location.create(:description => "San Nicolás de los Garza", :state_id => 19, :active => true)
  	Location.create(:description => "San Pedro Garza García", :state_id => 19, :active => true)
  	Location.create(:description => "Santa Catarina", :state_id => 19, :active => true)
  	Location.create(:description => "Santiago", :state_id => 19, :active => true)
  	Location.create(:description => "Vallecillo", :state_id => 19, :active => true)
  	Location.create(:description => "Villaldama", :state_id => 19, :active => true)

  end

  def down
    Country.delete_all
    State.delete_all
    Location.delete_all
  end
end
